name: App Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Get previous commit
      uses: actions/github-script@v4
      with:
        script: |
          const commits = await github.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 2
          });
          const previousCommit = commits.data[1].sha;
          console.log(previousCommit);
      
    - name: Zip the Build
      run: |
        ls target/release
        tar cvzf system-monitor_musl_amd64.tar.gz -C ./target/x86_64-unknown-linux-musl/release system-monitor
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          system-monitor_musl_amd64.tar.gz